version: "3"

services:
  # Postgres
  db:
    container_name: kantin_db
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./query:/docker-entrypoint-initdb.d/
      - ./data/pgdata:/var/lib/postgresql/data

  # Main service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kantin_backend
    ports:
      - "${USER_PORT}:${USER_PORT}"
      - "${SELLER_PORT}:${SELLER_PORT}"
    depends_on:
      - db
    environment:
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SECRET=${DB_SECRET}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - USER_PORT=${USER_PORT}
      - SELLER_PORT=${SELLER_PORT}
    links:
      - "postgres"
